//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ailment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ailment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIMS.Model.Resources.Ailment", typeof(Ailment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ailment.
        /// </summary>
        public static string AddAilment {
            get {
                return ResourceManager.GetString("AddAilment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment Code.
        /// </summary>
        public static string AilmentCode {
            get {
                return ResourceManager.GetString("AilmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment Master.
        /// </summary>
        public static string AilmentMaster {
            get {
                return ResourceManager.GetString("AilmentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment Name.
        /// </summary>
        public static string AilmentName {
            get {
                return ResourceManager.GetString("AilmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Ailment Code.
        /// </summary>
        public static string EAilmentCode {
            get {
                return ResourceManager.GetString("EAilmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Ailment Name.
        /// </summary>
        public static string EAilmentName {
            get {
                return ResourceManager.GetString("EAilmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment Code is required..
        /// </summary>
        public static string RAilmentCode {
            get {
                return ResourceManager.GetString("RAilmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment code must not exceed 10 characters..
        /// </summary>
        public static string RAilmentCodeLength {
            get {
                return ResourceManager.GetString("RAilmentCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliment Name is required..
        /// </summary>
        public static string RAilmentName {
            get {
                return ResourceManager.GetString("RAilmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment Master.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ailment.
        /// </summary>
        public static string ViewAilment {
            get {
                return ResourceManager.GetString("ViewAilment", resourceCulture);
            }
        }
    }
}
