//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Breed {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Breed() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIMS.Model.Resources.Breed", typeof(Breed).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Breed.
        /// </summary>
        public static string AddBreed {
            get {
                return ResourceManager.GetString("AddBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Code.
        /// </summary>
        public static string BreedCode {
            get {
                return ResourceManager.GetString("BreedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed.
        /// </summary>
        public static string Breede {
            get {
                return ResourceManager.GetString("Breede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Master.
        /// </summary>
        public static string BreedMaster {
            get {
                return ResourceManager.GetString("BreedMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Name.
        /// </summary>
        public static string BreedName {
            get {
                return ResourceManager.GetString("BreedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Breed Code.
        /// </summary>
        public static string EBreedCode {
            get {
                return ResourceManager.GetString("EBreedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Breed Name.
        /// </summary>
        public static string EBreedName {
            get {
                return ResourceManager.GetString("EBreedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Code is required..
        /// </summary>
        public static string RBreedCode {
            get {
                return ResourceManager.GetString("RBreedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed code must not exceed 10 characters..
        /// </summary>
        public static string RBreedCodeLength {
            get {
                return ResourceManager.GetString("RBreedCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Name is required..
        /// </summary>
        public static string RBreedName {
            get {
                return ResourceManager.GetString("RBreedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Code is required..
        /// </summary>
        public static string RSpeciesCode {
            get {
                return ResourceManager.GetString("RSpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Species.
        /// </summary>
        public static string SelectSpecies {
            get {
                return ResourceManager.GetString("SelectSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Code.
        /// </summary>
        public static string SpeciesCode {
            get {
                return ResourceManager.GetString("SpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Speciese {
            get {
                return ResourceManager.GetString("Speciese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Master.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Breed.
        /// </summary>
        public static string ViewBreed {
            get {
                return ResourceManager.GetString("ViewBreed", resourceCulture);
            }
        }
    }
}
