//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Doctor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Doctor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIMS.Model.Resources.Doctor", typeof(Doctor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Doctor.
        /// </summary>
        public static string AddDoctor {
            get {
                return ResourceManager.GetString("AddDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 1.
        /// </summary>
        public static string ContactNumber1 {
            get {
                return ResourceManager.GetString("ContactNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number 2.
        /// </summary>
        public static string ContactNumber2 {
            get {
                return ResourceManager.GetString("ContactNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Code.
        /// </summary>
        public static string DoctorCode {
            get {
                return ResourceManager.GetString("DoctorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Master.
        /// </summary>
        public static string DoctorMaster {
            get {
                return ResourceManager.GetString("DoctorMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string EAddress {
            get {
                return ResourceManager.GetString("EAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contact Number 1.
        /// </summary>
        public static string EContactNumber1 {
            get {
                return ResourceManager.GetString("EContactNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contact Number 2.
        /// </summary>
        public static string EContactNumber2 {
            get {
                return ResourceManager.GetString("EContactNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Doctor.
        /// </summary>
        public static string EditDoctor {
            get {
                return ResourceManager.GetString("EditDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter DoctorCode.
        /// </summary>
        public static string EDoctorCode {
            get {
                return ResourceManager.GetString("EDoctorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EName {
            get {
                return ResourceManager.GetString("EName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string EndingDate {
            get {
                return ResourceManager.GetString("EndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EPassword {
            get {
                return ResourceManager.GetString("EPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin Code.
        /// </summary>
        public static string EPinCode {
            get {
                return ResourceManager.GetString("EPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Qualifications.
        /// </summary>
        public static string EQualifications {
            get {
                return ResourceManager.GetString("EQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Address.
        /// </summary>
        public static string RAddress {
            get {
                return ResourceManager.GetString("RAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select City.
        /// </summary>
        public static string RCityId {
            get {
                return ResourceManager.GetString("RCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Contact Number 1.
        /// </summary>
        public static string RContactNumber1 {
            get {
                return ResourceManager.GetString("RContactNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Date Of Birth.
        /// </summary>
        public static string RDateOfBirth {
            get {
                return ResourceManager.GetString("RDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Doctor Code.
        /// </summary>
        public static string RDoctorCode {
            get {
                return ResourceManager.GetString("RDoctorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Doctor Name.
        /// </summary>
        public static string RDoctorName {
            get {
                return ResourceManager.GetString("RDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Ending Date.
        /// </summary>
        public static string REndingDate {
            get {
                return ResourceManager.GetString("REndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select Gender.
        /// </summary>
        public static string RGender {
            get {
                return ResourceManager.GetString("RGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Joining Date.
        /// </summary>
        public static string RJoiningDate {
            get {
                return ResourceManager.GetString("RJoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Password.
        /// </summary>
        public static string RPassword {
            get {
                return ResourceManager.GetString("RPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter PicCode.
        /// </summary>
        public static string RPinCode {
            get {
                return ResourceManager.GetString("RPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Qualification.
        /// </summary>
        public static string RQualifications {
            get {
                return ResourceManager.GetString("RQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select Role.
        /// </summary>
        public static string RRoleId {
            get {
                return ResourceManager.GetString("RRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Signature.
        /// </summary>
        public static string RSignaturePath {
            get {
                return ResourceManager.GetString("RSignaturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select State.
        /// </summary>
        public static string RStateId {
            get {
                return ResourceManager.GetString("RStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Master.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Doctors.
        /// </summary>
        public static string ViewDoctors {
            get {
                return ResourceManager.GetString("ViewDoctors", resourceCulture);
            }
        }
    }
}
