//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Species {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Species() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIMS.Model.Resources.Species", typeof(Species).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Species.
        /// </summary>
        public static string AddSpecies {
            get {
                return ResourceManager.GetString("AddSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Species Code.
        /// </summary>
        public static string ESpeciesCode {
            get {
                return ResourceManager.GetString("ESpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Species Name.
        /// </summary>
        public static string ESpeciesName {
            get {
                return ResourceManager.GetString("ESpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Code is required..
        /// </summary>
        public static string RSpeciesCode {
            get {
                return ResourceManager.GetString("RSpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species code must not exceed 10 characters..
        /// </summary>
        public static string RSpeciesCodeLength {
            get {
                return ResourceManager.GetString("RSpeciesCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Name is required..
        /// </summary>
        public static string RSpeciesName {
            get {
                return ResourceManager.GetString("RSpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Code.
        /// </summary>
        public static string SpeciesCode {
            get {
                return ResourceManager.GetString("SpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Speciese {
            get {
                return ResourceManager.GetString("Speciese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Master.
        /// </summary>
        public static string SpeciesMaster {
            get {
                return ResourceManager.GetString("SpeciesMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Name.
        /// </summary>
        public static string SpeciesName {
            get {
                return ResourceManager.GetString("SpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Master.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Species.
        /// </summary>
        public static string ViewSpecies {
            get {
                return ResourceManager.GetString("ViewSpecies", resourceCulture);
            }
        }
    }
}
