//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VIMSEntities : DbContext
    {
        public VIMSEntities()
            : base("name=VIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SpeciesMaster> SpeciesMasters { get; set; }
    
        public virtual ObjectResult<string> VIMS_AilmentMasterInsUpd(Nullable<int> ailmentId, string ailmentCode, string ailmentName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var ailmentIdParameter = ailmentId.HasValue ?
                new ObjectParameter("AilmentId", ailmentId) :
                new ObjectParameter("AilmentId", typeof(int));
    
            var ailmentCodeParameter = ailmentCode != null ?
                new ObjectParameter("AilmentCode", ailmentCode) :
                new ObjectParameter("AilmentCode", typeof(string));
    
            var ailmentNameParameter = ailmentName != null ?
                new ObjectParameter("AilmentName", ailmentName) :
                new ObjectParameter("AilmentName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_AilmentMasterInsUpd", ailmentIdParameter, ailmentCodeParameter, ailmentNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_AilmentMasterRtr_Result> VIMS_AilmentMasterRtr(Nullable<int> ailmentId, string ailmentCode, string action)
        {
            var ailmentIdParameter = ailmentId.HasValue ?
                new ObjectParameter("AilmentId", ailmentId) :
                new ObjectParameter("AilmentId", typeof(int));
    
            var ailmentCodeParameter = ailmentCode != null ?
                new ObjectParameter("AilmentCode", ailmentCode) :
                new ObjectParameter("AilmentCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_AilmentMasterRtr_Result>("VIMS_AilmentMasterRtr", ailmentIdParameter, ailmentCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_BreedMasterInsUpd(Nullable<int> breedId, string breedCode, string breedName, string speciesCode, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var breedIdParameter = breedId.HasValue ?
                new ObjectParameter("BreedId", breedId) :
                new ObjectParameter("BreedId", typeof(int));
    
            var breedCodeParameter = breedCode != null ?
                new ObjectParameter("BreedCode", breedCode) :
                new ObjectParameter("BreedCode", typeof(string));
    
            var breedNameParameter = breedName != null ?
                new ObjectParameter("BreedName", breedName) :
                new ObjectParameter("BreedName", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_BreedMasterInsUpd", breedIdParameter, breedCodeParameter, breedNameParameter, speciesCodeParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_BreedMasterRtr_Result> VIMS_BreedMasterRtr(Nullable<int> breedId, string breedCode, string speciesCode, string action)
        {
            var breedIdParameter = breedId.HasValue ?
                new ObjectParameter("BreedId", breedId) :
                new ObjectParameter("BreedId", typeof(int));
    
            var breedCodeParameter = breedCode != null ?
                new ObjectParameter("BreedCode", breedCode) :
                new ObjectParameter("BreedCode", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_BreedMasterRtr_Result>("VIMS_BreedMasterRtr", breedIdParameter, breedCodeParameter, speciesCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_SpeciesMasterInsUpd(Nullable<int> speciesId, string speciesName, string speciesCode, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var speciesIdParameter = speciesId.HasValue ?
                new ObjectParameter("SpeciesId", speciesId) :
                new ObjectParameter("SpeciesId", typeof(int));
    
            var speciesNameParameter = speciesName != null ?
                new ObjectParameter("SpeciesName", speciesName) :
                new ObjectParameter("SpeciesName", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_SpeciesMasterInsUpd", speciesIdParameter, speciesNameParameter, speciesCodeParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_SpeciesMasterRtr_Result> VIMS_SpeciesMasterRtr(Nullable<int> speciesId, string speciesCode, string action)
        {
            var speciesIdParameter = speciesId.HasValue ?
                new ObjectParameter("SpeciesId", speciesId) :
                new ObjectParameter("SpeciesId", typeof(int));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_SpeciesMasterRtr_Result>("VIMS_SpeciesMasterRtr", speciesIdParameter, speciesCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_ChangePassword(string societyCode, string oldpassword, string newpassword, string createDate)
        {
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var oldpasswordParameter = oldpassword != null ?
                new ObjectParameter("Oldpassword", oldpassword) :
                new ObjectParameter("Oldpassword", typeof(string));
    
            var newpasswordParameter = newpassword != null ?
                new ObjectParameter("Newpassword", newpassword) :
                new ObjectParameter("Newpassword", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_ChangePassword", societyCodeParameter, oldpasswordParameter, newpasswordParameter, createDateParameter);
        }
    
        public virtual ObjectResult<string> VIMS_IntePageModuleInsUpd(Nullable<int> inteId, Nullable<int> moduleId, Nullable<int> pageId, string createdBy, Nullable<bool> isActive, string action)
        {
            var inteIdParameter = inteId.HasValue ?
                new ObjectParameter("InteId", inteId) :
                new ObjectParameter("InteId", typeof(int));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_IntePageModuleInsUpd", inteIdParameter, moduleIdParameter, pageIdParameter, createdByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_IntePageModuleRtr_Result> VIMS_IntePageModuleRtr(string action, Nullable<int> moduleId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_IntePageModuleRtr_Result>("VIMS_IntePageModuleRtr", actionParameter, moduleIdParameter);
        }
    
        public virtual ObjectResult<string> VIMS_InteRoleModuleInsUpd(Nullable<int> inteId, Nullable<int> roleId, string modid, Nullable<int> mPInteId, Nullable<bool> isActive, Nullable<bool> viewRight, Nullable<bool> insertRight, Nullable<bool> updateRight, Nullable<bool> deleteRight, string createdBy, string updatedBy, string action)
        {
            var inteIdParameter = inteId.HasValue ?
                new ObjectParameter("InteId", inteId) :
                new ObjectParameter("InteId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var modidParameter = modid != null ?
                new ObjectParameter("Modid", modid) :
                new ObjectParameter("Modid", typeof(string));
    
            var mPInteIdParameter = mPInteId.HasValue ?
                new ObjectParameter("MPInteId", mPInteId) :
                new ObjectParameter("MPInteId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var viewRightParameter = viewRight.HasValue ?
                new ObjectParameter("ViewRight", viewRight) :
                new ObjectParameter("ViewRight", typeof(bool));
    
            var insertRightParameter = insertRight.HasValue ?
                new ObjectParameter("InsertRight", insertRight) :
                new ObjectParameter("InsertRight", typeof(bool));
    
            var updateRightParameter = updateRight.HasValue ?
                new ObjectParameter("UpdateRight", updateRight) :
                new ObjectParameter("UpdateRight", typeof(bool));
    
            var deleteRightParameter = deleteRight.HasValue ?
                new ObjectParameter("DeleteRight", deleteRight) :
                new ObjectParameter("DeleteRight", typeof(bool));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_InteRoleModuleInsUpd", inteIdParameter, roleIdParameter, modidParameter, mPInteIdParameter, isActiveParameter, viewRightParameter, insertRightParameter, updateRightParameter, deleteRightParameter, createdByParameter, updatedByParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_InteRoleModuleRtr_Result> VIMS_InteRoleModuleRtr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_InteRoleModuleRtr_Result>("VIMS_InteRoleModuleRtr");
        }
    
        public virtual ObjectResult<string> VIMS_ModuleMasterInsUpd(Nullable<int> moduleId, string moduleName, string gUModuleName, Nullable<int> modulePriority, Nullable<bool> isActive, Nullable<bool> isSelfURL, string faIcon, string createdBy, string updatedBy, string action)
        {
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var moduleNameParameter = moduleName != null ?
                new ObjectParameter("ModuleName", moduleName) :
                new ObjectParameter("ModuleName", typeof(string));
    
            var gUModuleNameParameter = gUModuleName != null ?
                new ObjectParameter("GUModuleName", gUModuleName) :
                new ObjectParameter("GUModuleName", typeof(string));
    
            var modulePriorityParameter = modulePriority.HasValue ?
                new ObjectParameter("ModulePriority", modulePriority) :
                new ObjectParameter("ModulePriority", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var isSelfURLParameter = isSelfURL.HasValue ?
                new ObjectParameter("IsSelfURL", isSelfURL) :
                new ObjectParameter("IsSelfURL", typeof(bool));
    
            var faIconParameter = faIcon != null ?
                new ObjectParameter("FaIcon", faIcon) :
                new ObjectParameter("FaIcon", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_ModuleMasterInsUpd", moduleIdParameter, moduleNameParameter, gUModuleNameParameter, modulePriorityParameter, isActiveParameter, isSelfURLParameter, faIconParameter, createdByParameter, updatedByParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_ModuleMasterRtr_Result> VIMS_ModuleMasterRtr(Nullable<int> moduleId, string action)
        {
            var moduleIdParameter = moduleId.HasValue ?
                new ObjectParameter("ModuleId", moduleId) :
                new ObjectParameter("ModuleId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_ModuleMasterRtr_Result>("VIMS_ModuleMasterRtr", moduleIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_PageMasterInsUpd(Nullable<int> pageId, string pageName, string gUPageName, string pageUrl, Nullable<int> pagePriority, Nullable<bool> isActive, Nullable<bool> isPdf, string createdBy, string updatedBy, string action)
        {
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(int));
    
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            var gUPageNameParameter = gUPageName != null ?
                new ObjectParameter("GUPageName", gUPageName) :
                new ObjectParameter("GUPageName", typeof(string));
    
            var pageUrlParameter = pageUrl != null ?
                new ObjectParameter("PageUrl", pageUrl) :
                new ObjectParameter("PageUrl", typeof(string));
    
            var pagePriorityParameter = pagePriority.HasValue ?
                new ObjectParameter("PagePriority", pagePriority) :
                new ObjectParameter("PagePriority", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var isPdfParameter = isPdf.HasValue ?
                new ObjectParameter("IsPdf", isPdf) :
                new ObjectParameter("IsPdf", typeof(bool));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_PageMasterInsUpd", pageIdParameter, pageNameParameter, gUPageNameParameter, pageUrlParameter, pagePriorityParameter, isActiveParameter, isPdfParameter, createdByParameter, updatedByParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_PageMasterRtr_Result> VIMS_PageMasterRtr(Nullable<int> pageId, string action)
        {
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_PageMasterRtr_Result>("VIMS_PageMasterRtr", pageIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_RoleMasterInsUpd(Nullable<int> roleId, string roleName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_RoleMasterInsUpd", roleIdParameter, roleNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_RoleMasterRtr_Result> VIMS_RoleMasterRtr(Nullable<int> roleId, string action)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_RoleMasterRtr_Result>("VIMS_RoleMasterRtr", roleIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_AdminMasterRtr_Result> VIMS_AdminMasterRtr(Nullable<int> adminId, string adminCode, string action)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            var adminCodeParameter = adminCode != null ?
                new ObjectParameter("AdminCode", adminCode) :
                new ObjectParameter("AdminCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_AdminMasterRtr_Result>("VIMS_AdminMasterRtr", adminIdParameter, adminCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_CityMasterInsUpd(Nullable<int> cityId, string cityCode, string cityName, Nullable<int> stateId, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var cityCodeParameter = cityCode != null ?
                new ObjectParameter("CityCode", cityCode) :
                new ObjectParameter("CityCode", typeof(string));
    
            var cityNameParameter = cityName != null ?
                new ObjectParameter("CityName", cityName) :
                new ObjectParameter("CityName", typeof(string));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_CityMasterInsUpd", cityIdParameter, cityCodeParameter, cityNameParameter, stateIdParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_CityMasterRtr_Result> VIMS_CityMasterRtr(Nullable<int> cityId, string cityCode, Nullable<int> stateId, string action)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var cityCodeParameter = cityCode != null ?
                new ObjectParameter("CityCode", cityCode) :
                new ObjectParameter("CityCode", typeof(string));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_CityMasterRtr_Result>("VIMS_CityMasterRtr", cityIdParameter, cityCodeParameter, stateIdParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_DoctorMasterRtr_Result> VIMS_DoctorMasterRtr(Nullable<int> doctorId, string doctorCode, string action)
        {
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("DoctorId", doctorId) :
                new ObjectParameter("DoctorId", typeof(int));
    
            var doctorCodeParameter = doctorCode != null ?
                new ObjectParameter("DoctorCode", doctorCode) :
                new ObjectParameter("DoctorCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_DoctorMasterRtr_Result>("VIMS_DoctorMasterRtr", doctorIdParameter, doctorCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_LoginCheck(string userCode, string password)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_LoginCheck", userCodeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> VIMS_StatesMasterInsUpd(Nullable<int> stateId, string stateCode, string stateName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var stateCodeParameter = stateCode != null ?
                new ObjectParameter("StateCode", stateCode) :
                new ObjectParameter("StateCode", typeof(string));
    
            var stateNameParameter = stateName != null ?
                new ObjectParameter("StateName", stateName) :
                new ObjectParameter("StateName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_StatesMasterInsUpd", stateIdParameter, stateCodeParameter, stateNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_StatesMasterRtr_Result> VIMS_StatesMasterRtr(Nullable<int> stateId, string stateCode, string action)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var stateCodeParameter = stateCode != null ?
                new ObjectParameter("StateCode", stateCode) :
                new ObjectParameter("StateCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_StatesMasterRtr_Result>("VIMS_StatesMasterRtr", stateIdParameter, stateCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_LoginRtr_Result> VIMS_LoginRtr(string userCode, string password)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_LoginRtr_Result>("VIMS_LoginRtr", userCodeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> VIMS_AdminMasterInsUpd(Nullable<int> adminId, string adminCode, string name, string gender, string dateOfBirth, string address, Nullable<int> cityId, Nullable<int> stateId, string pinCode, string contactNumber, string password, Nullable<int> roleId, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            var adminCodeParameter = adminCode != null ?
                new ObjectParameter("AdminCode", adminCode) :
                new ObjectParameter("AdminCode", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth != null ?
                new ObjectParameter("DateOfBirth", dateOfBirth) :
                new ObjectParameter("DateOfBirth", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_AdminMasterInsUpd", adminIdParameter, adminCodeParameter, nameParameter, genderParameter, dateOfBirthParameter, addressParameter, cityIdParameter, stateIdParameter, pinCodeParameter, contactNumberParameter, passwordParameter, roleIdParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_DoctorMasterInsUpd(Nullable<int> doctorId, string doctorCode, string name, string gender, string dateOfBirth, string address, Nullable<int> cityId, Nullable<int> stateId, string pinCode, string contactNumber1, string contactNumber2, string password, Nullable<int> roleId, string joiningDate, string endingDate, string qualifications, string signaturePath, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("DoctorId", doctorId) :
                new ObjectParameter("DoctorId", typeof(int));
    
            var doctorCodeParameter = doctorCode != null ?
                new ObjectParameter("DoctorCode", doctorCode) :
                new ObjectParameter("DoctorCode", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth != null ?
                new ObjectParameter("DateOfBirth", dateOfBirth) :
                new ObjectParameter("DateOfBirth", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(int));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            var contactNumber1Parameter = contactNumber1 != null ?
                new ObjectParameter("ContactNumber1", contactNumber1) :
                new ObjectParameter("ContactNumber1", typeof(string));
    
            var contactNumber2Parameter = contactNumber2 != null ?
                new ObjectParameter("ContactNumber2", contactNumber2) :
                new ObjectParameter("ContactNumber2", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var joiningDateParameter = joiningDate != null ?
                new ObjectParameter("JoiningDate", joiningDate) :
                new ObjectParameter("JoiningDate", typeof(string));
    
            var endingDateParameter = endingDate != null ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(string));
    
            var qualificationsParameter = qualifications != null ?
                new ObjectParameter("Qualifications", qualifications) :
                new ObjectParameter("Qualifications", typeof(string));
    
            var signaturePathParameter = signaturePath != null ?
                new ObjectParameter("SignaturePath", signaturePath) :
                new ObjectParameter("SignaturePath", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_DoctorMasterInsUpd", doctorIdParameter, doctorCodeParameter, nameParameter, genderParameter, dateOfBirthParameter, addressParameter, cityIdParameter, stateIdParameter, pinCodeParameter, contactNumber1Parameter, contactNumber2Parameter, passwordParameter, roleIdParameter, joiningDateParameter, endingDateParameter, qualificationsParameter, signaturePathParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_CustomerMasterInsUpd(Nullable<int> customerId, string societyCode, string customerCode, string name, string address, string contactNumber1, string contactNumber2, Nullable<int> roleId, string password, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var contactNumber1Parameter = contactNumber1 != null ?
                new ObjectParameter("ContactNumber1", contactNumber1) :
                new ObjectParameter("ContactNumber1", typeof(string));
    
            var contactNumber2Parameter = contactNumber2 != null ?
                new ObjectParameter("ContactNumber2", contactNumber2) :
                new ObjectParameter("ContactNumber2", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_CustomerMasterInsUpd", customerIdParameter, societyCodeParameter, customerCodeParameter, nameParameter, addressParameter, contactNumber1Parameter, contactNumber2Parameter, roleIdParameter, passwordParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_CustomerMasterRtr_Result> VIMS_CustomerMasterRtr(Nullable<int> customerId, string customerCode, string societyCode, string action)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_CustomerMasterRtr_Result>("VIMS_CustomerMasterRtr", customerIdParameter, customerCodeParameter, societyCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_AgeGroupMasterInsUpd(Nullable<int> ageGroupId, string ageGroupCode, string ageGroupName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var ageGroupIdParameter = ageGroupId.HasValue ?
                new ObjectParameter("AgeGroupId", ageGroupId) :
                new ObjectParameter("AgeGroupId", typeof(int));
    
            var ageGroupCodeParameter = ageGroupCode != null ?
                new ObjectParameter("AgeGroupCode", ageGroupCode) :
                new ObjectParameter("AgeGroupCode", typeof(string));
    
            var ageGroupNameParameter = ageGroupName != null ?
                new ObjectParameter("AgeGroupName", ageGroupName) :
                new ObjectParameter("AgeGroupName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_AgeGroupMasterInsUpd", ageGroupIdParameter, ageGroupCodeParameter, ageGroupNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_AgeGroupMasterRtr_Result> VIMS_AgeGroupMasterRtr(Nullable<int> ageGroupId, string ageGroupCode, string action)
        {
            var ageGroupIdParameter = ageGroupId.HasValue ?
                new ObjectParameter("AgeGroupId", ageGroupId) :
                new ObjectParameter("AgeGroupId", typeof(int));
    
            var ageGroupCodeParameter = ageGroupCode != null ?
                new ObjectParameter("AgeGroupCode", ageGroupCode) :
                new ObjectParameter("AgeGroupCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_AgeGroupMasterRtr_Result>("VIMS_AgeGroupMasterRtr", ageGroupIdParameter, ageGroupCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_BaseUnitMasterInsUpd(Nullable<int> baseUnitId, string baseUnitCode, string baseUnitName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var baseUnitIdParameter = baseUnitId.HasValue ?
                new ObjectParameter("BaseUnitId", baseUnitId) :
                new ObjectParameter("BaseUnitId", typeof(int));
    
            var baseUnitCodeParameter = baseUnitCode != null ?
                new ObjectParameter("BaseUnitCode", baseUnitCode) :
                new ObjectParameter("BaseUnitCode", typeof(string));
    
            var baseUnitNameParameter = baseUnitName != null ?
                new ObjectParameter("BaseUnitName", baseUnitName) :
                new ObjectParameter("BaseUnitName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_BaseUnitMasterInsUpd", baseUnitIdParameter, baseUnitCodeParameter, baseUnitNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_BaseUnitMasterRtr_Result> VIMS_BaseUnitMasterRtr(Nullable<int> baseUnitId, string baseUnitCode, string action)
        {
            var baseUnitIdParameter = baseUnitId.HasValue ?
                new ObjectParameter("BaseUnitId", baseUnitId) :
                new ObjectParameter("BaseUnitId", typeof(int));
    
            var baseUnitCodeParameter = baseUnitCode != null ?
                new ObjectParameter("BaseUnitCode", baseUnitCode) :
                new ObjectParameter("BaseUnitCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_BaseUnitMasterRtr_Result>("VIMS_BaseUnitMasterRtr", baseUnitIdParameter, baseUnitCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_CenterMasterInsUpd(Nullable<int> centerId, string plantCode, string centerCode, string centerName, Nullable<bool> autoAllocation, Nullable<int> noOfVisit, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var centerIdParameter = centerId.HasValue ?
                new ObjectParameter("CenterId", centerId) :
                new ObjectParameter("CenterId", typeof(int));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var centerCodeParameter = centerCode != null ?
                new ObjectParameter("CenterCode", centerCode) :
                new ObjectParameter("CenterCode", typeof(string));
    
            var centerNameParameter = centerName != null ?
                new ObjectParameter("CenterName", centerName) :
                new ObjectParameter("CenterName", typeof(string));
    
            var autoAllocationParameter = autoAllocation.HasValue ?
                new ObjectParameter("AutoAllocation", autoAllocation) :
                new ObjectParameter("AutoAllocation", typeof(bool));
    
            var noOfVisitParameter = noOfVisit.HasValue ?
                new ObjectParameter("NoOfVisit", noOfVisit) :
                new ObjectParameter("NoOfVisit", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_CenterMasterInsUpd", centerIdParameter, plantCodeParameter, centerCodeParameter, centerNameParameter, autoAllocationParameter, noOfVisitParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_CenterMasterRtr_Result> VIMS_CenterMasterRtr(Nullable<int> centerId, string centerCode, string plantCode, string action)
        {
            var centerIdParameter = centerId.HasValue ?
                new ObjectParameter("CenterId", centerId) :
                new ObjectParameter("CenterId", typeof(int));
    
            var centerCodeParameter = centerCode != null ?
                new ObjectParameter("CenterCode", centerCode) :
                new ObjectParameter("CenterCode", typeof(string));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_CenterMasterRtr_Result>("VIMS_CenterMasterRtr", centerIdParameter, centerCodeParameter, plantCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_DiseaseMasterInsUpd(Nullable<int> diseaseId, string diseaseCode, string diseaseName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var diseaseIdParameter = diseaseId.HasValue ?
                new ObjectParameter("DiseaseId", diseaseId) :
                new ObjectParameter("DiseaseId", typeof(int));
    
            var diseaseCodeParameter = diseaseCode != null ?
                new ObjectParameter("DiseaseCode", diseaseCode) :
                new ObjectParameter("DiseaseCode", typeof(string));
    
            var diseaseNameParameter = diseaseName != null ?
                new ObjectParameter("DiseaseName", diseaseName) :
                new ObjectParameter("DiseaseName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_DiseaseMasterInsUpd", diseaseIdParameter, diseaseCodeParameter, diseaseNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_DiseaseMasterRtr_Result> VIMS_DiseaseMasterRtr(Nullable<int> diseaseId, string diseaseCode, string action)
        {
            var diseaseIdParameter = diseaseId.HasValue ?
                new ObjectParameter("DiseaseId", diseaseId) :
                new ObjectParameter("DiseaseId", typeof(int));
    
            var diseaseCodeParameter = diseaseCode != null ?
                new ObjectParameter("DiseaseCode", diseaseCode) :
                new ObjectParameter("DiseaseCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_DiseaseMasterRtr_Result>("VIMS_DiseaseMasterRtr", diseaseIdParameter, diseaseCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_MedicineGroupMasterInsUpd(Nullable<int> medicineGroupId, string medicineGroupCode, string medicineGroupName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var medicineGroupIdParameter = medicineGroupId.HasValue ?
                new ObjectParameter("MedicineGroupId", medicineGroupId) :
                new ObjectParameter("MedicineGroupId", typeof(int));
    
            var medicineGroupCodeParameter = medicineGroupCode != null ?
                new ObjectParameter("MedicineGroupCode", medicineGroupCode) :
                new ObjectParameter("MedicineGroupCode", typeof(string));
    
            var medicineGroupNameParameter = medicineGroupName != null ?
                new ObjectParameter("MedicineGroupName", medicineGroupName) :
                new ObjectParameter("MedicineGroupName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_MedicineGroupMasterInsUpd", medicineGroupIdParameter, medicineGroupCodeParameter, medicineGroupNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_MedicineGroupMasterRtr_Result> VIMS_MedicineGroupMasterRtr(Nullable<int> medicineGroupId, string medicineGroupCode, string action)
        {
            var medicineGroupIdParameter = medicineGroupId.HasValue ?
                new ObjectParameter("MedicineGroupId", medicineGroupId) :
                new ObjectParameter("MedicineGroupId", typeof(int));
    
            var medicineGroupCodeParameter = medicineGroupCode != null ?
                new ObjectParameter("MedicineGroupCode", medicineGroupCode) :
                new ObjectParameter("MedicineGroupCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_MedicineGroupMasterRtr_Result>("VIMS_MedicineGroupMasterRtr", medicineGroupIdParameter, medicineGroupCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_MedicineMasterInsUpd(Nullable<int> medicineId, string medicineCode, string medicineName, string baseUnitCode, Nullable<decimal> baseCost, string routeCode, Nullable<bool> general, Nullable<bool> fA, Nullable<bool> camp, string issueUnit, Nullable<decimal> lowQty, Nullable<decimal> highQty, Nullable<bool> stockCalculation, Nullable<decimal> ratio, string medicineGroupCode, Nullable<int> noOfDays, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var medicineIdParameter = medicineId.HasValue ?
                new ObjectParameter("MedicineId", medicineId) :
                new ObjectParameter("MedicineId", typeof(int));
    
            var medicineCodeParameter = medicineCode != null ?
                new ObjectParameter("MedicineCode", medicineCode) :
                new ObjectParameter("MedicineCode", typeof(string));
    
            var medicineNameParameter = medicineName != null ?
                new ObjectParameter("MedicineName", medicineName) :
                new ObjectParameter("MedicineName", typeof(string));
    
            var baseUnitCodeParameter = baseUnitCode != null ?
                new ObjectParameter("BaseUnitCode", baseUnitCode) :
                new ObjectParameter("BaseUnitCode", typeof(string));
    
            var baseCostParameter = baseCost.HasValue ?
                new ObjectParameter("BaseCost", baseCost) :
                new ObjectParameter("BaseCost", typeof(decimal));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("RouteCode", routeCode) :
                new ObjectParameter("RouteCode", typeof(string));
    
            var generalParameter = general.HasValue ?
                new ObjectParameter("General", general) :
                new ObjectParameter("General", typeof(bool));
    
            var fAParameter = fA.HasValue ?
                new ObjectParameter("FA", fA) :
                new ObjectParameter("FA", typeof(bool));
    
            var campParameter = camp.HasValue ?
                new ObjectParameter("Camp", camp) :
                new ObjectParameter("Camp", typeof(bool));
    
            var issueUnitParameter = issueUnit != null ?
                new ObjectParameter("IssueUnit", issueUnit) :
                new ObjectParameter("IssueUnit", typeof(string));
    
            var lowQtyParameter = lowQty.HasValue ?
                new ObjectParameter("LowQty", lowQty) :
                new ObjectParameter("LowQty", typeof(decimal));
    
            var highQtyParameter = highQty.HasValue ?
                new ObjectParameter("HighQty", highQty) :
                new ObjectParameter("HighQty", typeof(decimal));
    
            var stockCalculationParameter = stockCalculation.HasValue ?
                new ObjectParameter("StockCalculation", stockCalculation) :
                new ObjectParameter("StockCalculation", typeof(bool));
    
            var ratioParameter = ratio.HasValue ?
                new ObjectParameter("Ratio", ratio) :
                new ObjectParameter("Ratio", typeof(decimal));
    
            var medicineGroupCodeParameter = medicineGroupCode != null ?
                new ObjectParameter("MedicineGroupCode", medicineGroupCode) :
                new ObjectParameter("MedicineGroupCode", typeof(string));
    
            var noOfDaysParameter = noOfDays.HasValue ?
                new ObjectParameter("NoOfDays", noOfDays) :
                new ObjectParameter("NoOfDays", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_MedicineMasterInsUpd", medicineIdParameter, medicineCodeParameter, medicineNameParameter, baseUnitCodeParameter, baseCostParameter, routeCodeParameter, generalParameter, fAParameter, campParameter, issueUnitParameter, lowQtyParameter, highQtyParameter, stockCalculationParameter, ratioParameter, medicineGroupCodeParameter, noOfDaysParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_MedicineMasterRtr_Result> VIMS_MedicineMasterRtr(Nullable<int> medicineId, string medicineCode, string medicineGroupCode, string routeCode, string baseUnitCode, string action)
        {
            var medicineIdParameter = medicineId.HasValue ?
                new ObjectParameter("MedicineId", medicineId) :
                new ObjectParameter("MedicineId", typeof(int));
    
            var medicineCodeParameter = medicineCode != null ?
                new ObjectParameter("MedicineCode", medicineCode) :
                new ObjectParameter("MedicineCode", typeof(string));
    
            var medicineGroupCodeParameter = medicineGroupCode != null ?
                new ObjectParameter("MedicineGroupCode", medicineGroupCode) :
                new ObjectParameter("MedicineGroupCode", typeof(string));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("RouteCode", routeCode) :
                new ObjectParameter("RouteCode", typeof(string));
    
            var baseUnitCodeParameter = baseUnitCode != null ?
                new ObjectParameter("BaseUnitCode", baseUnitCode) :
                new ObjectParameter("BaseUnitCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_MedicineMasterRtr_Result>("VIMS_MedicineMasterRtr", medicineIdParameter, medicineCodeParameter, medicineGroupCodeParameter, routeCodeParameter, baseUnitCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_PlantMasterInsUpd(Nullable<int> plantId, string plantCode, string plantName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var plantIdParameter = plantId.HasValue ?
                new ObjectParameter("PlantId", plantId) :
                new ObjectParameter("PlantId", typeof(int));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var plantNameParameter = plantName != null ?
                new ObjectParameter("PlantName", plantName) :
                new ObjectParameter("PlantName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_PlantMasterInsUpd", plantIdParameter, plantCodeParameter, plantNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_PlantMasterRtr_Result> VIMS_PlantMasterRtr(Nullable<int> plantId, string plantCode, string action)
        {
            var plantIdParameter = plantId.HasValue ?
                new ObjectParameter("PlantId", plantId) :
                new ObjectParameter("PlantId", typeof(int));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_PlantMasterRtr_Result>("VIMS_PlantMasterRtr", plantIdParameter, plantCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_RouteMasterInsUpd(Nullable<int> routeId, string routeCode, string routeName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var routeIdParameter = routeId.HasValue ?
                new ObjectParameter("RouteId", routeId) :
                new ObjectParameter("RouteId", typeof(int));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("RouteCode", routeCode) :
                new ObjectParameter("RouteCode", typeof(string));
    
            var routeNameParameter = routeName != null ?
                new ObjectParameter("RouteName", routeName) :
                new ObjectParameter("RouteName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_RouteMasterInsUpd", routeIdParameter, routeCodeParameter, routeNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_RouteMasterRtr_Result> VIMS_RouteMasterRtr(Nullable<int> routeId, string routeCode, string action)
        {
            var routeIdParameter = routeId.HasValue ?
                new ObjectParameter("RouteId", routeId) :
                new ObjectParameter("RouteId", typeof(int));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("RouteCode", routeCode) :
                new ObjectParameter("RouteCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_RouteMasterRtr_Result>("VIMS_RouteMasterRtr", routeIdParameter, routeCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_SampleMasterInsUpd(Nullable<int> sampleId, string sampleName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var sampleIdParameter = sampleId.HasValue ?
                new ObjectParameter("SampleId", sampleId) :
                new ObjectParameter("SampleId", typeof(int));
    
            var sampleNameParameter = sampleName != null ?
                new ObjectParameter("SampleName", sampleName) :
                new ObjectParameter("SampleName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_SampleMasterInsUpd", sampleIdParameter, sampleNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_SampleMasterRtr_Result> VIMS_SampleMasterRtr(Nullable<int> sampleId, string sampleName, string action)
        {
            var sampleIdParameter = sampleId.HasValue ?
                new ObjectParameter("SampleId", sampleId) :
                new ObjectParameter("SampleId", typeof(int));
    
            var sampleNameParameter = sampleName != null ?
                new ObjectParameter("SampleName", sampleName) :
                new ObjectParameter("SampleName", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_SampleMasterRtr_Result>("VIMS_SampleMasterRtr", sampleIdParameter, sampleNameParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_SymptomsMasterInsUpd(Nullable<int> symptomsId, string diseaseCode, string symptomsCode, string symptomsName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var symptomsIdParameter = symptomsId.HasValue ?
                new ObjectParameter("SymptomsId", symptomsId) :
                new ObjectParameter("SymptomsId", typeof(int));
    
            var diseaseCodeParameter = diseaseCode != null ?
                new ObjectParameter("DiseaseCode", diseaseCode) :
                new ObjectParameter("DiseaseCode", typeof(string));
    
            var symptomsCodeParameter = symptomsCode != null ?
                new ObjectParameter("SymptomsCode", symptomsCode) :
                new ObjectParameter("SymptomsCode", typeof(string));
    
            var symptomsNameParameter = symptomsName != null ?
                new ObjectParameter("SymptomsName", symptomsName) :
                new ObjectParameter("SymptomsName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_SymptomsMasterInsUpd", symptomsIdParameter, diseaseCodeParameter, symptomsCodeParameter, symptomsNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_SymptomsMasterRtr_Result> VIMS_SymptomsMasterRtr(Nullable<int> symptomsId, string symptomsCode, string diseaseCode, string action)
        {
            var symptomsIdParameter = symptomsId.HasValue ?
                new ObjectParameter("SymptomsId", symptomsId) :
                new ObjectParameter("SymptomsId", typeof(int));
    
            var symptomsCodeParameter = symptomsCode != null ?
                new ObjectParameter("SymptomsCode", symptomsCode) :
                new ObjectParameter("SymptomsCode", typeof(string));
    
            var diseaseCodeParameter = diseaseCode != null ?
                new ObjectParameter("DiseaseCode", diseaseCode) :
                new ObjectParameter("DiseaseCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_SymptomsMasterRtr_Result>("VIMS_SymptomsMasterRtr", symptomsIdParameter, symptomsCodeParameter, diseaseCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_VehicleMasterInsUpd(Nullable<int> vehicleId, string vendorCode, string vehicleCode, string vehicleRegisterNumber, Nullable<System.DateTime> vehicleRegisterDate, string model, Nullable<decimal> rate, Nullable<System.DateTime> rateEffectiveDate, Nullable<System.DateTime> contractStartDate, Nullable<System.DateTime> contractEndDate, Nullable<System.DateTime> insuranceCommitmentDate, Nullable<System.DateTime> insuranceExpiryDate, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var vehicleIdParameter = vehicleId.HasValue ?
                new ObjectParameter("VehicleId", vehicleId) :
                new ObjectParameter("VehicleId", typeof(int));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var vehicleCodeParameter = vehicleCode != null ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(string));
    
            var vehicleRegisterNumberParameter = vehicleRegisterNumber != null ?
                new ObjectParameter("VehicleRegisterNumber", vehicleRegisterNumber) :
                new ObjectParameter("VehicleRegisterNumber", typeof(string));
    
            var vehicleRegisterDateParameter = vehicleRegisterDate.HasValue ?
                new ObjectParameter("VehicleRegisterDate", vehicleRegisterDate) :
                new ObjectParameter("VehicleRegisterDate", typeof(System.DateTime));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("Rate", rate) :
                new ObjectParameter("Rate", typeof(decimal));
    
            var rateEffectiveDateParameter = rateEffectiveDate.HasValue ?
                new ObjectParameter("RateEffectiveDate", rateEffectiveDate) :
                new ObjectParameter("RateEffectiveDate", typeof(System.DateTime));
    
            var contractStartDateParameter = contractStartDate.HasValue ?
                new ObjectParameter("ContractStartDate", contractStartDate) :
                new ObjectParameter("ContractStartDate", typeof(System.DateTime));
    
            var contractEndDateParameter = contractEndDate.HasValue ?
                new ObjectParameter("ContractEndDate", contractEndDate) :
                new ObjectParameter("ContractEndDate", typeof(System.DateTime));
    
            var insuranceCommitmentDateParameter = insuranceCommitmentDate.HasValue ?
                new ObjectParameter("InsuranceCommitmentDate", insuranceCommitmentDate) :
                new ObjectParameter("InsuranceCommitmentDate", typeof(System.DateTime));
    
            var insuranceExpiryDateParameter = insuranceExpiryDate.HasValue ?
                new ObjectParameter("InsuranceExpiryDate", insuranceExpiryDate) :
                new ObjectParameter("InsuranceExpiryDate", typeof(System.DateTime));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_VehicleMasterInsUpd", vehicleIdParameter, vendorCodeParameter, vehicleCodeParameter, vehicleRegisterNumberParameter, vehicleRegisterDateParameter, modelParameter, rateParameter, rateEffectiveDateParameter, contractStartDateParameter, contractEndDateParameter, insuranceCommitmentDateParameter, insuranceExpiryDateParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_VehicleMasterRtr_Result> VIMS_VehicleMasterRtr(Nullable<int> vehicleId, string vehicleCode, string vendorCode, string action)
        {
            var vehicleIdParameter = vehicleId.HasValue ?
                new ObjectParameter("VehicleId", vehicleId) :
                new ObjectParameter("VehicleId", typeof(int));
    
            var vehicleCodeParameter = vehicleCode != null ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(string));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_VehicleMasterRtr_Result>("VIMS_VehicleMasterRtr", vehicleIdParameter, vehicleCodeParameter, vendorCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_VendorMasterInsUpd(Nullable<int> vendorId, string plantCode, string vendorCode, string vendorName, string address, string mobileNumber1, string mobileNumber2, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var mobileNumber1Parameter = mobileNumber1 != null ?
                new ObjectParameter("MobileNumber1", mobileNumber1) :
                new ObjectParameter("MobileNumber1", typeof(string));
    
            var mobileNumber2Parameter = mobileNumber2 != null ?
                new ObjectParameter("MobileNumber2", mobileNumber2) :
                new ObjectParameter("MobileNumber2", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_VendorMasterInsUpd", vendorIdParameter, plantCodeParameter, vendorCodeParameter, vendorNameParameter, addressParameter, mobileNumber1Parameter, mobileNumber2Parameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_VendorMasterRtr_Result> VIMS_VendorMasterRtr(Nullable<int> vendorId, string vendorCode, string plantCode, string action)
        {
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var plantCodeParameter = plantCode != null ?
                new ObjectParameter("PlantCode", plantCode) :
                new ObjectParameter("PlantCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_VendorMasterRtr_Result>("VIMS_VendorMasterRtr", vendorIdParameter, vendorCodeParameter, plantCodeParameter, actionParameter);
        }
    }
}
