//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VIMSEntities : DbContext
    {
        public VIMSEntities()
            : base("name=VIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SpeciesMaster> SpeciesMasters { get; set; }
    
        public virtual ObjectResult<string> VIMS_AilmentMasterInsUpd(Nullable<int> ailmentId, string ailmentCode, string ailmentName, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var ailmentIdParameter = ailmentId.HasValue ?
                new ObjectParameter("AilmentId", ailmentId) :
                new ObjectParameter("AilmentId", typeof(int));
    
            var ailmentCodeParameter = ailmentCode != null ?
                new ObjectParameter("AilmentCode", ailmentCode) :
                new ObjectParameter("AilmentCode", typeof(string));
    
            var ailmentNameParameter = ailmentName != null ?
                new ObjectParameter("AilmentName", ailmentName) :
                new ObjectParameter("AilmentName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_AilmentMasterInsUpd", ailmentIdParameter, ailmentCodeParameter, ailmentNameParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_AilmentMasterRtr_Result> VIMS_AilmentMasterRtr(Nullable<int> ailmentId, string ailmentCode, string action)
        {
            var ailmentIdParameter = ailmentId.HasValue ?
                new ObjectParameter("AilmentId", ailmentId) :
                new ObjectParameter("AilmentId", typeof(int));
    
            var ailmentCodeParameter = ailmentCode != null ?
                new ObjectParameter("AilmentCode", ailmentCode) :
                new ObjectParameter("AilmentCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_AilmentMasterRtr_Result>("VIMS_AilmentMasterRtr", ailmentIdParameter, ailmentCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_BreedMasterInsUpd(Nullable<int> breedId, string breedCode, string breedName, string speciesCode, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var breedIdParameter = breedId.HasValue ?
                new ObjectParameter("BreedId", breedId) :
                new ObjectParameter("BreedId", typeof(int));
    
            var breedCodeParameter = breedCode != null ?
                new ObjectParameter("BreedCode", breedCode) :
                new ObjectParameter("BreedCode", typeof(string));
    
            var breedNameParameter = breedName != null ?
                new ObjectParameter("BreedName", breedName) :
                new ObjectParameter("BreedName", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_BreedMasterInsUpd", breedIdParameter, breedCodeParameter, breedNameParameter, speciesCodeParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_BreedMasterRtr_Result> VIMS_BreedMasterRtr(Nullable<int> breedId, string breedCode, string speciesCode, string action)
        {
            var breedIdParameter = breedId.HasValue ?
                new ObjectParameter("BreedId", breedId) :
                new ObjectParameter("BreedId", typeof(int));
    
            var breedCodeParameter = breedCode != null ?
                new ObjectParameter("BreedCode", breedCode) :
                new ObjectParameter("BreedCode", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_BreedMasterRtr_Result>("VIMS_BreedMasterRtr", breedIdParameter, breedCodeParameter, speciesCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_SpeciesMasterInsUpd(Nullable<int> speciesId, string speciesName, string speciesCode, string createdBy, string updatedBy, Nullable<bool> isActive, string action)
        {
            var speciesIdParameter = speciesId.HasValue ?
                new ObjectParameter("SpeciesId", speciesId) :
                new ObjectParameter("SpeciesId", typeof(int));
    
            var speciesNameParameter = speciesName != null ?
                new ObjectParameter("SpeciesName", speciesName) :
                new ObjectParameter("SpeciesName", typeof(string));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_SpeciesMasterInsUpd", speciesIdParameter, speciesNameParameter, speciesCodeParameter, createdByParameter, updatedByParameter, isActiveParameter, actionParameter);
        }
    
        public virtual ObjectResult<VIMS_SpeciesMasterRtr_Result> VIMS_SpeciesMasterRtr(Nullable<int> speciesId, string speciesCode, string action)
        {
            var speciesIdParameter = speciesId.HasValue ?
                new ObjectParameter("SpeciesId", speciesId) :
                new ObjectParameter("SpeciesId", typeof(int));
    
            var speciesCodeParameter = speciesCode != null ?
                new ObjectParameter("SpeciesCode", speciesCode) :
                new ObjectParameter("SpeciesCode", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_SpeciesMasterRtr_Result>("VIMS_SpeciesMasterRtr", speciesIdParameter, speciesCodeParameter, actionParameter);
        }
    
        public virtual ObjectResult<string> VIMS_LoginCheck(string societyCode, string password)
        {
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_LoginCheck", societyCodeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<VIMS_LoginRtr_Result> VIMS_LoginRtr(string societyCode, string password)
        {
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIMS_LoginRtr_Result>("VIMS_LoginRtr", societyCodeParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> VIMS_ChangePassword(string societyCode, string oldpassword, string newpassword, string createDate)
        {
            var societyCodeParameter = societyCode != null ?
                new ObjectParameter("SocietyCode", societyCode) :
                new ObjectParameter("SocietyCode", typeof(string));
    
            var oldpasswordParameter = oldpassword != null ?
                new ObjectParameter("Oldpassword", oldpassword) :
                new ObjectParameter("Oldpassword", typeof(string));
    
            var newpasswordParameter = newpassword != null ?
                new ObjectParameter("Newpassword", newpassword) :
                new ObjectParameter("Newpassword", typeof(string));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIMS_ChangePassword", societyCodeParameter, oldpasswordParameter, newpasswordParameter, createDateParameter);
        }
    }
}
